opcua_client/urls.py
# opcua_client/urls.py

from django.urls import path
from . import views
app_name = "opcua_client"
urlpatterns = [
    path("start_dashboard/", views.start_dashboard, name="start_dashboard"),
    path(
        "get_node_information/", views.get_node_information, name="get_node_information"
    ),
    path(
        "monitor_realtime_variables/",
        views.monitor_realtime_variables,
        name="monitor_realtime_variables",
    ),
    path("call-method/", views.process_method_request, name="process_method_request"),
    path("end-connection/", views.end_connection, name="end_connection"),
    path("generate_graph/", views.generate_graph, name="generate_graph"),
    path("delete_graph/", views.delete_graph, name="delete_graph"),
    path('download_data/', views.download_data, name='download_data')
]

opcua_fusion/urls.py
# opcua_fusion/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("opcua_client.urls")),
    path("", include("opcua_aggregation_home.urls")),
    path("cloud_managements/", include("cloud_managements.urls")),
]

opcua_client/models.py
from django.db import models

# Create your models here.

opcua_client/views.py
# opcua_client/views.py

from django.shortcuts import render
from datetime import datetime, timezone
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from opcua import Client
from opcua.ua import NodeClass
import json, re, os, time, pytz
from tzlocal import get_localzone
import asyncio
import firebase_admin
from firebase_admin import credentials, firestore
from google.cloud.firestore_v1.base_query import FieldFilter
from concurrent.futures import ThreadPoolExecutor
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
matplotlib.use("Agg")


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
firebase_config_path = os.path.join(BASE_DIR, "serviceAccountKey.json") #substitute with environment variable in production
cred = credentials.Certificate(firebase_config_path)
firebase_admin.initialize_app(
    cred,
    {"storageBucket": "opcuafusion.appspot.com"},
)

stop_events = {}
executor = ThreadPoolExecutor(max_workers=10)


async def start_dashboard(request):

    endpoint = request.GET.get("endpoint", "opc.tcp://0.0.0.0:4840/my_cnc")
    namespaceuri = request.GET.get("namespaceuri", "my_cnc_namespace")
    machine = request.GET.get("machine", "generic_machine")

    try:
        client = Client(endpoint)
        client.connect()
        client.load_type_definitions()
        proceed = True
    except Exception as e:
        proceed = False
        data = {}
        method = {}

        timestamp = datetime.now(timezone.utc)

        db = firestore.client()

        failed_connections_ref = db.collection("failed_connections")

        query = failed_connections_ref.where("endpoint", "==", endpoint).limit(1)
        existing_docs = list(query.stream())

        if existing_docs:
            pass
        else:

            failed_connections_data = {
                "machine": machine,
                "endpoint": endpoint,
                "namespaceuri": namespaceuri,
                "timestamp": timestamp,
                "status": "Failed to connect",
            }

            failed_connections_doc_ref = failed_connections_ref.add(
                failed_connections_data
            )[1]
            failed_connections_id = failed_connections_doc_ref.id

        print(
            "Error in start_dashboard connection: Connection Failed: Server Endpoint Not Set Up"
        )

        context = {
            "error_message": f"Connection Failed: {str(e)}",
            "instruction": "The Endpoint or Namespace URI is incorrect. Please check it again.",
            "endpoint": endpoint,
        }
        return render(request, "opcua_client/connection_error.html", context)

    if proceed:
        try:

            db = firestore.client()

            current_connections_ref = db.collection("current_connections")

            query = current_connections_ref.where("endpoint", "==", endpoint).limit(1)
            existing_docs = list(query.stream())

            if existing_docs:
                context = {
                    "error_message": f"Endpoint already in use in another instance",
                    "instruction": "Please check the endpoint, or close every instance and try again.",
                }
                return render(request, "opcua_client/connection_error.html", context)
            else:
                start_timestamp = datetime.now(timezone.utc)
                current_connections_data = {
                "machine": machine,
                "endpoint": endpoint,
                "namespaceuri": namespaceuri,
                "timestamp": start_timestamp,
            }
            current_connections_doc_ref = current_connections_ref.add(
                current_connections_data
            )[1]
            current_connections_id = current_connections_doc_ref.id

            endpoint_collection_ref = db.collection("endpoint_info")
            endpoint_doc_data = {
                "endpoint": endpoint,
                "last_updated_timestamp": start_timestamp,
            }

            query = endpoint_collection_ref.where("endpoint", "==", endpoint).get()

            if not query:

                endpoint_doc_ref = endpoint_collection_ref.add(endpoint_doc_data)[1]
                current_endpoint_id = endpoint_doc_ref.id
            else:

                for doc in query:
                    current_endpoint_id = doc.id

            timestamp_current = datetime.now(timezone.utc)

            connection_doc_data = {
                "start_timestamp": start_timestamp,
                "stop_timestamp": None,
                "endpoint_id": current_endpoint_id,
                "namespaceuri": namespaceuri,
                "machine": machine,
                "full_node_info_id": None,
                "connection_status": True,
                "last_update_timestamp": timestamp_current,
            }

            connection_collection_ref = db.collection("connection_info")
            connection_doc_ref = connection_collection_ref.add(connection_doc_data)[1]
            connection_info_id = connection_doc_ref.id

        except Exception as e:
            print(
                "Error in start_dashboard function databases either endpoint_info or connection_info:",
                e,
            )

        object_node = client.get_objects_node()
        data = browse_node_names(object_node)
        method = browse_method_nodes(object_node)
        full_node_doc_data = browse_node_full(object_node)

        try:
            full_node_collection_ref = db.collection("full_node_info")
            timestamp_current = datetime.now(timezone.utc)
            full_node_doc_data["last_update_timestamp"] = timestamp_current
            full_node_doc_ref = full_node_collection_ref.add(full_node_doc_data)[1]
            full_node_doc_current_id = full_node_doc_ref.id

            connection_doc_ref = (
                db.collection("connection_info")
                .document(connection_info_id)
                .update(
                    {
                        "full_node_info_id": full_node_doc_current_id,
                        "last_update_timestamp": datetime.now(timezone.utc),
                    }
                )
            )
        except Exception as e:
            print("Error in start_dashboard function databases full_node_info:", e)
        stop_events[connection_info_id] = asyncio.Event()

        stop_events[connection_info_id].clear()
        loop = asyncio.get_event_loop()
        loop.run_in_executor(
            executor,
            asyncio.run,
            database_update_variables(
                object_node, current_endpoint_id, connection_info_id, db, client
            ),
        )

    context = {
        "data": data,
        "endpoint": endpoint,
        "method_context": method,
        "start_timestamp": str(start_timestamp),
        "namespaceuri": namespaceuri,
        "connection_id": {connection_info_id},
    }

    return render(request, "opcua_client/display_dashboard.html", context)


async def database_update_variables(
    node, current_endpoint_id, connection_info_id, db, client
):
    current_stop_event = stop_events[connection_info_id]
    while not current_stop_event.is_set():
        try:
            variables = {}
            variables_from_server = get_variables_with_client_timestamp(node, client)
            variables["endpoint_id"] = current_endpoint_id
            variables["realtime_variables_from_server"] = variables_from_server
            variables["client_timestamp"] = variables[
                "realtime_variables_from_server"
            ].pop("client_timestamp")
            variables["connection_info_id"] = connection_info_id
            database_name = "realtime_variable_" + str(current_endpoint_id)
            realtime_variable_collection_ref = db.collection(database_name)
            variables["last_update_timestamp"] = datetime.now(timezone.utc)
            try:
                if type(
                    variables["realtime_variables_from_server"]["server_timestamp"]
                ) == type(""):
                    variables["server_to_clientUI_in_seconds"] = ""
                else:
                    variables["server_to_clientUI_in_seconds"] = (
                        variables["client_timestamp"]
                        - variables["realtime_variables_from_server"][
                            "server_timestamp"
                        ]
                    ).total_seconds()
            except Exception as e:
                print(
                    "Error in database_update_variable function finding server_timestamp:",
                    e,
                )

            realtime_variable_doc_ref = realtime_variable_collection_ref.add(variables)[
                1
            ]
            realtime_variable_doc_current_id = realtime_variable_doc_ref.id
            await asyncio.sleep(0.0001)
        except Exception as e:
            print("Error in database_update_variable function:", e)

    if current_stop_event.is_set():

        client.disconnect()
        print("Disconnected from the server.")


async def end_connection(request):
    try:

        data = json.loads(request.body)
        endpoint = data.get("endpoint")
        try:
            start_timestamp_str = data.get("start_timestamp")
            start_timestamp = datetime.fromisoformat(start_timestamp_str)
            start_timestamp_utc = start_timestamp.astimezone(timezone.utc)
        except:
            print("error")

        try:

            db = firestore.client()

            connection_collection_ref = db.collection("connection_info")

            endpoint_collection_ref = db.collection("endpoint_info")

            if endpoint_query := endpoint_collection_ref.where(
                "endpoint", "==", endpoint
            ).get():
                for doc in endpoint_query:
                    current_endpoint_id = doc.id

opcua_client/templates/opcua_client/connection_error.html
<!-- opcua_client/templates/opcua_client/connection_error.html -->
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    {% csrf_token %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'opcua_client/css/connection_error.css' %}">
</head>
<body>
    <div class="container">
        <h1>Error</h1>
        {% if endpoint %}
            <p id="endpoint-value" hidden>{{ endpoint }}</p>
        {% endif %}
        <p>{{ error_message }}</p>
        <p>{{ instruction }}</p>
        <p>Please close this tab manually, or click the button below:</p>
        <button onclick="closeTab()">Close Tab</button>
    </div>
    <script>
        function closeTab() {
            var endpointElement = document.getElementById('endpoint-value');
            if (endpointElement) {
                var endpoint = endpointElement.textContent.trim();
                var csrfToken = document.querySelector('[name=csrfmiddlewaretoken]').value;


                fetch('/remove_connection/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'X-CSRFToken': csrfToken
                    },
                    body: JSON.stringify({ endpoint: endpoint })
                })
                .then(response => response.json())
                .then(data => {
                    console.log('Connection ended:', data.message);
                    
                    window.close();
                })
                .catch(error => {
                    console.error('Error ending the connection:', error);
                    
                    window.close();
                });
            } else {
                
                window.close();
            }
        }
    </script>
</body>
</html>

opcua_client/templates/opcua_client/download_data.html
<!-- opcua_client/templates/opcua_client/download_data.html -->
 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Download Data</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'opcua_client/css/download_data.css' %}">
    <script>
        function submitForm() {
            
            let fromDateInput = document.getElementById("from_date").value;
            let toDateInput = document.getElementById("to_date").value;

            if (!fromDateInput || !toDateInput) {
                alert("Please select both 'From Date' and 'To Date'.");
                return;
            }

            let fromDate = new Date(fromDateInput);
            let toDate = new Date(toDateInput);

            if (toDate <= fromDate) {
                alert("'To Date' must be after 'From Date'.");
                return;
            }

            fromDate = fromDate.toISOString();
            toDate = toDate.toISOString();

            
            let endpoint = "{{ endpoint }}";

            let requestData = {
                'from_date': fromDate,
                'to_date': toDate,
                'endpoint': endpoint
            };

            fetch("{% url 'opcua_client:download_data' %}", {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                body: JSON.stringify(requestData)
            })
            .then(response => {
                if (response.status === 200) {
                    return response.blob();
                } else {
                    return response.json().then(data => {throw new Error(data.message)});
                }
            })
            .then(blob => {
             
                let url = window.URL.createObjectURL(blob);
                let a = document.createElement('a');
                a.href = url;
                a.download = `data_${new Date().toISOString()}.csv`;
                document.body.appendChild(a);
                a.click();
                a.remove();
            })
            .catch(error => {
                alert("Error: " + error.message);
            });
        }
    </script>
</head>
<body>
    <h1>Download Data: {{ endpoint }} <br> namespaceuri: {{namespaceuri}}</h1>

    <span>Download Variables Data:</span>

    <form method="POST">
        {% csrf_token %}

       
        <label for="from_date">From (Date and Time):</label>
        <input type="datetime-local" id="from_date" name="from_date">

        <label for="to_date">To (Date and Time):</label>
        <input type="datetime-local" id="to_date" name="to_date">

        <button type="button" onclick="submitForm()">Download CSV</button>
    </form>
</body>
</html>

opcua_client/templates/opcua_client/generate_graph.html
<!-- opcua_client/templates/opcua_client/generate_graph.html -->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Generate Graph</title>
    {% load static %} {% csrf_token %}
    <link
      rel="stylesheet"
      href="{% static 'opcua_client/css/generate_graph.css' %}"
    />
    <script>
      function addVariableToX() {
        let xAxisDropdown = document.getElementById("x-axis-dropdown");
        let selectedValue = xAxisDropdown.value;

        let variablesForX = document.getElementById("variables_for_x").children;
        for (let i = 1; i < variablesForX.length; i++) {
          if (variablesForX[i].textContent === selectedValue) {
            alert("This variable is already added to the X axis.");
            return;
          }
        }

        if (selectedValue) {
          let variablesForX = document.getElementById("variables_for_x");
          let newDiv = document.createElement("div");
          newDiv.textContent = selectedValue;
          variablesForX.appendChild(newDiv);
        }
      }

      function addVariableToY() {
        let yAxisDropdown = document.getElementById("y-axis-dropdown");
        let selectedValue = yAxisDropdown.value;

        let variablesForY = document.getElementById("variables_for_y").children;
        for (let i = 1; i < variablesForY.length; i++) {
          if (variablesForY[i].textContent === selectedValue) {
            alert("This variable is already added to the Y axis.");
            return;
          }
        }

        if (selectedValue) {
          let variablesForY = document.getElementById("variables_for_y");
          let newDiv = document.createElement("div");
          newDiv.textContent = selectedValue;
          variablesForY.appendChild(newDiv);
        }
      }

      function addFromDate() {
        let fromDateInput = document.getElementById("from_date").value;
        if (fromDateInput) {
          let fromDateDiv = document.getElementById("from_date_div");
          fromDateDiv.innerHTML =
            "<h3>From Date:</h3>" +
            "<div id='from_date_value'>" +
            fromDateInput +
            "</div>";
        }
      }

      function addToDate() {
        let fromDateInput = document.getElementById("from_date").value;
        let toDateInput = document.getElementById("to_date").value;

        if (!fromDateInput) {
          alert("Please select a valid 'From Date' first.");
          return;
        }

        if (toDateInput) {
          let fromDate = new Date(fromDateInput);
          let toDate = new Date(toDateInput);

          if (toDate > fromDate) {
            let toDateDiv = document.getElementById("to_date_div");
            toDateDiv.innerHTML =
              "<h3>To Date:</h3>" +
              "<div id='to_date_value'>" +
              toDateInput +
              "</div>";
          } else {
            alert("'To Date' should be after 'From Date'. Please select a valid date.");
          }
        }
      }

      function resetSelections() {
        document.getElementById("variables_for_x").innerHTML =
          "<h3>X Axis Variables:</h3>";
        document.getElementById("variables_for_y").innerHTML =
          "<h3>Y Axis Variables:</h3>";
        document.getElementById("from_date_div").innerHTML =
          "<h3>From Date:</h3>";
        document.getElementById("to_date_div").innerHTML =
          "<h3>To Date:</h3>";
      }

      function submitForm() {
        let xAxisVariables = [];
        let variablesForX = document.getElementById("variables_for_x").children;
        for (let i = 1; i < variablesForX.length; i++) {
          xAxisVariables.push(variablesForX[i].textContent);
        }

        let yAxisVariables = [];
        let variablesForY = document.getElementById("variables_for_y").children;
        for (let i = 1; i < variablesForY.length; i++) {
          yAxisVariables.push(variablesForY[i].textContent);
        }

        let fromDate = document.getElementById("from_date_value")
          ? document.getElementById("from_date_value").textContent
          : null;
        if (fromDate) {
          fromDate = new Date(fromDate);
          fromDate = fromDate.toISOString();
        }

        let toDate = document.getElementById("to_date_value")
          ? document.getElementById("to_date_value").textContent
          : null;
        if (toDate) {
          toDate = new Date(toDate);
          toDate = toDate.toISOString();
        }

        if (!fromDate || !toDate) {
          alert("Please ensure both 'From Date' and 'To Date' are selected.");
          return;
        }

        let endpoint = "{{ endpoint }}";

        let requestData = {
          x_axis_variables: xAxisVariables,
          y_axis_variables: yAxisVariables,
          from_date: fromDate,
          to_date: toDate,
          endpoint: endpoint,
        };

        fetch("{% url 'opcua_client:generate_graph' %}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": document.querySelector(
              "[name=csrfmiddlewaretoken]"
            ).value,
          },
          body: JSON.stringify(requestData),
        })
          .then((response) => {
            if (!response.ok) {
              return response.json().then((errorData) => {
                throw new Error(
                  errorData.message || "Failed to generate the graph."
                );
              });
            }
            return response.json();
          })
          .then((data) => {
            location.reload();
          })
          .catch((error) => {
            alert(`Error: ${error.message}`);
          });
      }

      function deleteGraph(image_url) {
        let imageName = image_url.split("/").pop();

        fetch("{% url 'opcua_client:delete_graph' %}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": document.querySelector(
              "[name=csrfmiddlewaretoken]"
            ).value,
          },
          body: JSON.stringify({ image_name: imageName }),
        })
          .then((response) => response.json())
          .then((data) => {
            if (data.status === "success") {
              location.reload();
            } else {
              alert("Error deleting image: " + data.message);
            }
          })
          .catch((error) => console.error("Error:", error));
      }
    </script>
  </head>
  <body>
    <h1>
      Generate Graphs: {{ endpoint }} <br />
      namespaceuri: {{namespaceuri}}
    </h1>

    <form method="POST">
      {% csrf_token %}
      <label for="x-axis-dropdown">Add to x axis:</label>
      <select id="x-axis-dropdown" name="x_axis_values">
        {% for key in variables_data.keys %}
        <option value="{{ key }}">{{ key }}</option>
        {% endfor %}
      </select>
      <button type="button" onclick="addVariableToX()">Add</button>

      <label for="y-axis-dropdown">Add to y axis:</label>
      <select id="y-axis-dropdown" name="y_axis_values">
        {% for key in variables_data.keys %}
        <option value="{{ key }}">{{ key }}</option>
        {% endfor %}
      </select>
      <button type="button" onclick="addVariableToY()">Add</button>

      <label for="from_date">From (Date and Time):</label>
      <input type="datetime-local" id="from_date" name="from_date" />
      <button type="button" onclick="addFromDate()">Add</button>

      <label for="to_date">To (Date and Time):</label>
      <input type="datetime-local" id="to_date" name="to_date" />
      <button type="button" onclick="addToDate()">Add</button>

      <div id="variables_for_x">
        <h3>X Axis Variables:</h3>
      </div>
      <div id="variables_for_y">
        <h3>Y Axis Variables:</h3>
      </div>
      <div id="from_date_div">
        <h3>From Date:</h3>
      </div>
      <div id="to_date_div">
        <h3>To Date:</h3>
      </div>

      <button type="button" onclick="submitForm()">Generate Graph</button>
      <button type="button" onclick="resetSelections()">Reset</button>
    </form>

    <div id="image-gallery">
      <h2>Generated Graphs:</h2>
      {% for image_url in image_urls %}
      <div>
        <img src="{% static image_url %}" alt="Generated Graph" />
        <button type="button" onclick="deleteGraph('{% static image_url %}')">
          Delete
        </button>
      </div>
      {% endfor %}
    </div>
  </body>
</html>